version: "3.8"

services:
  bot:
    build: . 
    command: python3 src/main.py
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - cache

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes: 
      - pgdata:/var/lib/postgresql/data 
    restart: on-failure
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6380'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    environment:
      - REDIS_USERNAME
      - REDIS_PASSWORD
volumes:
  pgdata:
  cache:
    driver: local

